//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "cyclic_processes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: TimeDateTimeWithTimeZone,
    pub last_updated_at: Option<TimeDateTimeWithTimeZone>,
    pub status: String,
    pub started_at: Option<TimeDateTimeWithTimeZone>,
    pub paused_at: Option<TimeDateTimeWithTimeZone>,
    pub cycle_interval: i32,
    pub elapsed: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cyclic_process_resources::Entity")]
    CyclicProcessResources,
    #[sea_orm(has_many = "super::monks::Entity")]
    Monks,
    #[sea_orm(has_many = "super::players::Entity")]
    Players,
    #[sea_orm(has_many = "super::sources::Entity")]
    Sources,
}

impl Related<super::cyclic_process_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CyclicProcessResources.def()
    }
}

impl Related<super::monks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Monks.def()
    }
}

impl Related<super::players::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Players.def()
    }
}

impl Related<super::sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sources.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
