//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "game")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub player_id: i32,
    pub monastery_id: i32,
    pub surroundings_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::monastery::Entity",
        from = "Column::MonasteryId",
        to = "super::monastery::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Monastery,
    #[sea_orm(
        belongs_to = "super::player::Entity",
        from = "Column::PlayerId",
        to = "super::player::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Player,
    #[sea_orm(
        belongs_to = "super::surroundings::Entity",
        from = "Column::SurroundingsId",
        to = "super::surroundings::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Surroundings,
}

impl Related<super::monastery::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Monastery.def()
    }
}

impl Related<super::player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Player.def()
    }
}

impl Related<super::surroundings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Surroundings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
