//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "games")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub player_id: i32,
    pub monastery_id: i32,
    pub surroundings_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::monasteries::Entity",
        from = "Column::MonasteryId",
        to = "super::monasteries::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Monasteries,
    #[sea_orm(
        belongs_to = "super::players::Entity",
        from = "Column::PlayerId",
        to = "super::players::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Players,
    #[sea_orm(
        belongs_to = "super::surroundings::Entity",
        from = "Column::SurroundingsId",
        to = "super::surroundings::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Surroundings,
    #[sea_orm(has_one = "super::user_games::Entity")]
    UserGames,
}

impl Related<super::monasteries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Monasteries.def()
    }
}

impl Related<super::players::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Players.def()
    }
}

impl Related<super::surroundings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Surroundings.def()
    }
}

impl Related<super::user_games::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGames.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
