//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub mod prelude;

pub mod cyclic_process_resources;
pub mod cyclic_processes;
pub mod games;
pub mod monasteries;
pub mod monastery_monks;
pub mod monk_skills;
pub mod monks;
pub mod players;
pub mod resources;
pub mod skills;
pub mod sources;
pub mod surroundings;
pub mod surroundings_sources;
pub mod users;
