//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub mod prelude;

pub mod cyclic_process;
pub mod game;
pub mod monastery;
pub mod player;
pub mod surroundings;

seaography::register_entity_modules!([cyclic_process, game, monastery, player, surroundings,]);
