//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "monastery_monks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub monastery_id: i32,
    pub monk_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::monasteries::Entity",
        from = "Column::MonasteryId",
        to = "super::monasteries::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Monasteries,
    #[sea_orm(
        belongs_to = "super::monks::Entity",
        from = "Column::MonkId",
        to = "super::monks::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Monks,
}

impl Related<super::monasteries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Monasteries.def()
    }
}

impl Related<super::monks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Monks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
