//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "monks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub assigned_cyclic_process_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cyclic_processes::Entity",
        from = "Column::AssignedCyclicProcessId",
        to = "super::cyclic_processes::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    CyclicProcesses,
    #[sea_orm(has_many = "super::monastery_monks::Entity")]
    MonasteryMonks,
    #[sea_orm(has_many = "super::monk_skills::Entity")]
    MonkSkills,
}

impl Related<super::cyclic_processes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CyclicProcesses.def()
    }
}

impl Related<super::monastery_monks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MonasteryMonks.def()
    }
}

impl Related<super::monk_skills::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MonkSkills.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
