//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "players")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: TimeDateTimeWithTimeZone,
    pub last_updated_at: Option<TimeDateTimeWithTimeZone>,
    pub assigned_process_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cyclic_processes::Entity",
        from = "Column::AssignedProcessId",
        to = "super::cyclic_processes::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    CyclicProcesses,
    #[sea_orm(has_many = "super::games::Entity")]
    Games,
}

impl Related<super::cyclic_processes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CyclicProcesses.def()
    }
}

impl Related<super::games::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Games.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
