//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "player")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub assigned_process_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cyclic_process::Entity",
        from = "Column::AssignedProcessId",
        to = "super::cyclic_process::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    CyclicProcess,
    #[sea_orm(has_many = "super::game::Entity")]
    Game,
}

impl Related<super::cyclic_process::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CyclicProcess.def()
    }
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
