//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::cyclic_process::Entity as CyclicProcess;
pub use super::game::Entity as Game;
pub use super::monastery::Entity as Monastery;
pub use super::player::Entity as Player;
pub use super::surroundings::Entity as Surroundings;
