//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::cyclic_process_resources::Entity as CyclicProcessResources;
pub use super::cyclic_processes::Entity as CyclicProcesses;
pub use super::games::Entity as Games;
pub use super::monasteries::Entity as Monasteries;
pub use super::monastery_monks::Entity as MonasteryMonks;
pub use super::monk_skills::Entity as MonkSkills;
pub use super::monks::Entity as Monks;
pub use super::players::Entity as Players;
pub use super::resources::Entity as Resources;
pub use super::skills::Entity as Skills;
pub use super::sources::Entity as Sources;
pub use super::surroundings::Entity as Surroundings;
