//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "resources")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub category: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cyclic_process_resources::Entity")]
    CyclicProcessResources,
}

impl Related<super::cyclic_process_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CyclicProcessResources.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
