//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "sources")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub cyclic_process_id: i32,
    pub last_claim_at: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cyclic_processes::Entity",
        from = "Column::CyclicProcessId",
        to = "super::cyclic_processes::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    CyclicProcesses,
}

impl Related<super::cyclic_processes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CyclicProcesses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
