//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "surroundings_sources")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub surroundings_id: i32,
    pub source_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sources::Entity",
        from = "Column::SurroundingsId",
        to = "super::sources::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Sources,
    #[sea_orm(
        belongs_to = "super::surroundings::Entity",
        from = "Column::SurroundingsId",
        to = "super::surroundings::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Surroundings,
}

impl Related<super::sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sources.def()
    }
}

impl Related<super::surroundings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Surroundings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
