//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "tasks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: TimeDateTimeWithTimeZone,
    pub last_updated_at: Option<TimeDateTimeWithTimeZone>,
    pub status: String,
    pub started_at: Option<TimeDateTimeWithTimeZone>,
    pub paused_at: Option<TimeDateTimeWithTimeZone>,
    pub duration: i32,
    pub elapsed: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::task_input_resources::Entity")]
    TaskInputResources,
    #[sea_orm(has_many = "super::task_output_resources::Entity")]
    TaskOutputResources,
}

impl Related<super::task_input_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskInputResources.def()
    }
}

impl Related<super::task_output_resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskOutputResources.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
