[package]
name = "api"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
domain = { path = "../domain" }
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
time = { workspace = true }
dotenvy = "0.15.7"
utoipa = { workspace = true }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
tower-cookies = { workspace = true }
tower-http = { version = "0.6.8", features = ["cors"] }

[dev-dependencies]
serde_json = { workspace = true }
migration = { path = "../migration" }
sea-orm = { workspace = true }
tower = "0.5.2"
serial_test = "3.2.0"
