// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AssignData, AssignErrors, AssignResponses, GetSessionGameData, GetSessionGameErrors, GetSessionGameResponses, GetSessionUserData, GetSessionUserErrors, GetSessionUserResponses, LoginData, LoginErrors, LoginResponses, PauseData, PauseErrors, PauseResponses, RefreshData, RefreshErrors, RefreshResponses, RegisterData, RegisterErrors, RegisterResponses, StartData, StartErrors, StartResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Handles a login attempt of User.
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Handles a refresh attempt of a User.
 */
export const refresh = <ThrowOnError extends boolean = false>(options: Options<RefreshData, ThrowOnError>) => (options.client ?? client).post<RefreshResponses, RefreshErrors, ThrowOnError>({ url: '/api/auth/refresh', ...options });

/**
 * Registers a new User.
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Assigns a cyclic process to an actor.
 */
export const assign = <ThrowOnError extends boolean = false>(options: Options<AssignData, ThrowOnError>) => (options.client ?? client).post<AssignResponses, AssignErrors, ThrowOnError>({
    url: '/api/cyclic-processes/assign',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Starts a cyclic process.
 */
export const pause = <ThrowOnError extends boolean = false>(options: Options<PauseData, ThrowOnError>) => (options.client ?? client).post<PauseResponses, PauseErrors, ThrowOnError>({ url: '/api/cyclic-processes/{process_id}/pause', ...options });

/**
 * Starts a cyclic process.
 */
export const start = <ThrowOnError extends boolean = false>(options: Options<StartData, ThrowOnError>) => (options.client ?? client).post<StartResponses, StartErrors, ThrowOnError>({ url: '/api/cyclic-processes/{process_id}/start', ...options });

/**
 * Gets a User for the provided session.
 */
export const getSessionGame = <ThrowOnError extends boolean = false>(options?: Options<GetSessionGameData, ThrowOnError>) => (options?.client ?? client).get<GetSessionGameResponses, GetSessionGameErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/games/me',
    ...options
});

/**
 * Gets a User for the provided session.
 */
export const getSessionUser = <ThrowOnError extends boolean = false>(options?: Options<GetSessionUserData, ThrowOnError>) => (options?.client ?? client).get<GetSessionUserResponses, GetSessionUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/me',
    ...options
});
