// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type AppError = {
    /**
     * The message code of the error.
     */
    code: string;
    /**
     * The context of the error.
     */
    context?: {
        [key: string]: string;
    } | null;
    /**
     * The message of the error.
     */
    message: string;
};

/**
 * Represents a [CyclicProcess] DTO.
 */
export type CyclicProcessDto = {
    /**
     * The cycle duration of the CyclicProcess.
     */
    cycle_interval: string;
    /**
     * The time that has elapsed since the CyclicProcess was started.
     */
    elapsed: string;
    /**
     * The ID of the CyclicProcess.
     */
    id: number;
    /**
     * The time the CyclicProcess was paused last.
     */
    paused_at?: string | null;
    /**
     * The time the CyclicProcess was started last.
     */
    started_at?: string | null;
    /**
     * The status of the CyclicProcess.
     */
    status: string;
};

/**
 * A Game DTO.
 */
export type GameDto = {
    /**
     * The ID of the Game.
     */
    id: number;
    /**
     * The Monastery DTO.
     */
    monastery: MonasteryDto;
    /**
     * The Player DTO.
     */
    player: PlayerDto;
    /**
     * The Surroundings DTO.
     */
    surroundings: SurroundingsDto;
};

/**
 * Represents the payload used to login a user.
 */
export type LoginUserRequest = {
    /**
     * The email address of the user to login with.
     */
    email?: string | null;
    /**
     * The password of the user to login with.
     */
    password?: string | null;
};

/**
 * Represents the response used when a user was logged-in.
 */
export type LoginUserResponse = {
    /**
     * The session token for the logged-in user.
     */
    session_token: string;
};

/**
 * Represents a [Monastery] DTO.
 */
export type MonasteryDto = {
    /**
     * The ID of the Monastery.
     */
    id: number;
    /**
     * The Monks of the Monastery.
     */
    monks: Array<MonkDto>;
};

/**
 * Represents a Monk DTO.
 */
export type MonkDto = {
    assigned_process?: null | ProcessDto;
    /**
     * The ID of the Monk.
     */
    id: number;
    /**
     * The name of the Monk.
     */
    name: string;
    /**
     * The IDs  of the Monk skills.
     */
    skill_ids: Array<number>;
};

/**
 * Represents a [Player] DTO.
 */
export type PlayerDto = {
    /**
     * The ID of the Player.
     */
    id: number;
    process?: null | ProcessDto;
};

/**
 * Represents a request to assign a Process to an Actor, and the other way around.
 */
export type ProcessAssignmentRequest = {
    /**
     * The IDs of the Actors to assign.
     */
    actor_ids: Array<number>;
    /**
     * Indicates whether to assign the Player to the process.
     */
    assign_player: boolean;
    /**
     * The ID of the Process to assign.
     */
    process_id: number;
};

export type ProcessDto = (CyclicProcessDto & {
    type: 'CyclicProcess';
}) | (TaskDto & {
    type: 'Task';
});

/**
 * Represents the payload used to register a new user.
 */
export type RegisterUserRequest = {
    /**
     * The confirmed password of the user to register.
     */
    confirmed_password?: string | null;
    /**
     * The email address of the user to register.
     */
    email?: string | null;
    /**
     * The password of the user to register.
     */
    password?: string | null;
};

/**
 * Represents the response used when a new user was registered.
 */
export type RegisterUserResponse = {
    /**
     * The email address of the registered user.
     */
    email: string;
    /**
     * The ID of the registered user.
     */
    id: number;
};

/**
 * Represents a [Source] DTO.
 */
export type SourceDto = {
    /**
     * The ID of the Source.
     */
    id: number;
    /**
     * The last time a claim was made for the output of the completed cycles of the Source.
     */
    last_claim_at?: string | null;
    /**
     * The name of the Source.
     */
    name: string;
    /**
     * The process of the Source.
     */
    process: CyclicProcessDto;
};

/**
 * Represents a [Surroundings] DTO.
 */
export type SurroundingsDto = {
    /**
     * The ID of the Surroundings.
     */
    id: number;
    /**
     * The Sources  of the Surroundings.
     */
    sources: Array<SourceDto>;
};

export type TaskDto = {
    /**
     * The duration of this Task.
     */
    duration: string;
    /**
     * The time that has elapsed since the Task was started.
     */
    elapsed: string;
    /**
     * The ID of the Task.
     */
    id: number;
    /**
     * The time the Task was paused last.
     */
    paused_at?: string | null;
    /**
     * The time the Task was started last.
     */
    started_at?: string | null;
    /**
     * The status of the Task.
     */
    status: string;
};

/**
 * Represents a [User] DTO.
 */
export type UserDto = {
    /**
     * The email address of the user.
     */
    email: string;
    /**
     * The ID of the user.
     */
    id: number;
};

export type LoginData = {
    body: LoginUserRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * The login attempt failed due to wrong credentials.
     */
    401: AppError;
    /**
     * The login attempt failed due to an error.
     */
    500: AppError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * The login attempt was successful.
     */
    200: LoginUserResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshErrors = {
    /**
     * The refresh attempt failed due to an error.
     */
    500: AppError;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * The refresh attempt was successful.
     */
    200: LoginUserResponse;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type RegisterData = {
    body: RegisterUserRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterErrors = {
    /**
     * The user was not registered due to an error.
     */
    500: AppError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * The user was registered.
     */
    200: RegisterUserResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type AssignData = {
    body: ProcessAssignmentRequest;
    path?: never;
    query?: never;
    url: '/api/cyclic-processes/assign';
};

export type AssignErrors = {
    /**
     * The cyclic process was not able to be assigned due to you being anonymous.
     */
    401: AppError;
    /**
     * The cyclic process was not found.
     */
    404: AppError;
    /**
     * The cyclic process was not able to be assigned due to an error.
     */
    500: AppError;
};

export type AssignError = AssignErrors[keyof AssignErrors];

export type AssignResponses = {
    /**
     * The cyclic process has been assigned to an actor.
     */
    200: CyclicProcessDto;
};

export type AssignResponse = AssignResponses[keyof AssignResponses];

export type PauseData = {
    body?: never;
    path: {
        process_id: number;
    };
    query?: never;
    url: '/api/cyclic-processes/{process_id}/pause';
};

export type PauseErrors = {
    /**
     * The cyclic process was not able to pause due to you being anonymous.
     */
    401: AppError;
    /**
     * The cyclic process was not found.
     */
    404: AppError;
    /**
     * The cyclic process was not able to pause due to an error.
     */
    500: AppError;
};

export type PauseError = PauseErrors[keyof PauseErrors];

export type PauseResponses = {
    /**
     * The cyclic process has been paused.
     */
    200: CyclicProcessDto;
};

export type PauseResponse = PauseResponses[keyof PauseResponses];

export type StartData = {
    body?: never;
    path: {
        process_id: number;
    };
    query?: never;
    url: '/api/cyclic-processes/{process_id}/start';
};

export type StartErrors = {
    /**
     * The cyclic process was not able to start due to you being anonymous.
     */
    401: AppError;
    /**
     * The cyclic process was not found.
     */
    404: AppError;
    /**
     * The cyclic process was not able to start due to an error.
     */
    500: AppError;
};

export type StartError = StartErrors[keyof StartErrors];

export type StartResponses = {
    /**
     * The cyclic process has started.
     */
    200: CyclicProcessDto;
};

export type StartResponse = StartResponses[keyof StartResponses];

export type GetSessionGameData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/games/me';
};

export type GetSessionGameErrors = {
    /**
     * Failed to authenticate a user.
     */
    401: AppError;
    /**
     * Failed to find a game for the provided ID.
     */
    404: AppError;
};

export type GetSessionGameError = GetSessionGameErrors[keyof GetSessionGameErrors];

export type GetSessionGameResponses = {
    /**
     * The game was found.
     */
    200: GameDto;
};

export type GetSessionGameResponse = GetSessionGameResponses[keyof GetSessionGameResponses];

export type GetSessionUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetSessionUserErrors = {
    /**
     * Failed to authenticate a user.
     */
    401: AppError;
};

export type GetSessionUserError = GetSessionUserErrors[keyof GetSessionUserErrors];

export type GetSessionUserResponses = {
    /**
     * The user was found.
     */
    200: UserDto;
};

export type GetSessionUserResponse = GetSessionUserResponses[keyof GetSessionUserResponses];
